#
# Copyright (C) 2023 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

CXXEXT = .cpp

CXXSRCS += libutils/Errors.cpp
CXXSRCS += libutils/FileMap.cpp
CXXSRCS += libutils/JenkinsHash.cpp
CXXSRCS += libutils/LightRefBase.cpp
CXXSRCS += libutils/Looper.cpp
CXXSRCS += libutils/misc.cpp
CXXSRCS += libutils/NativeHandle.cpp
CXXSRCS += libutils/Printer.cpp
CXXSRCS += libutils/RefBase.cpp
CXXSRCS += libutils/SharedBuffer.cpp
CXXSRCS += libutils/StopWatch.cpp
CXXSRCS += libutils/String8.cpp
CXXSRCS += libutils/String16.cpp
CXXSRCS += libutils/StrongPointer.cpp
CXXSRCS += libutils/SystemClock.cpp
CXXSRCS += libutils/Threads.cpp
CXXSRCS += libutils/Timers.cpp
CXXSRCS += libutils/Tokenizer.cpp
CXXSRCS += libutils/Unicode.cpp
CXXSRCS += libutils/VectorImpl.cpp

include $(APPDIR)/Application.mk
