#
# Copyright (C) 2023 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

CXXEXT = .cpp

CXXSRCS += libbase/abi_compatibility.cpp
CXXSRCS += libbase/chrono_utils.cpp
CXXSRCS += libbase/cmsg.cpp
CXXSRCS += libbase/errors_unix.cpp
CXXSRCS += libbase/file.cpp
CXXSRCS += libbase/hex.cpp
CXXSRCS += libbase/logging.cpp
CXXSRCS += libbase/mapped_file.cpp
CXXSRCS += libbase/parsebool.cpp
CXXSRCS += libbase/parsenetaddress.cpp
CXXSRCS += libbase/posix_strerror_r.cpp
CXXSRCS += libbase/process.cpp
CXXSRCS += libbase/properties.cpp
CXXSRCS += libbase/stringprintf.cpp
CXXSRCS += libbase/strings.cpp
CXXSRCS += libbase/test_utils.cpp
CXXSRCS += libbase/threads.cpp

include $(APPDIR)/Application.mk
