#
# Copyright (C) 2023 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

CXXEXT = .cpp

CXXSRCS += binder/aidl/android/app/ProcessStateEnum.cpp
CXXSRCS += binder/aidl/android/content/pm/ApexStagedEvent.cpp
CXXSRCS += binder/aidl/android/content/pm/IPackageChangeObserver.cpp
CXXSRCS += binder/aidl/android/content/pm/IPackageManagerNative.cpp
CXXSRCS += binder/aidl/android/content/pm/IStagedApexObserver.cpp
CXXSRCS += binder/aidl/android/content/pm/PackageChangeEvent.cpp
CXXSRCS += binder/aidl/android/content/pm/StagedApexInfo.cpp
CXXSRCS += binder/aidl/android/os/ConnectionInfo.cpp
CXXSRCS += binder/aidl/android/os/IClientCallback.cpp
CXXSRCS += binder/aidl/android/os/IServiceCallback.cpp
CXXSRCS += binder/aidl/android/os/IServiceManager.cpp
CXXSRCS += binder/aidl/android/os/ServiceDebugInfo.cpp

CXXSRCS += binder/ndk/status.cpp

CXXSRCS += binder/ActivityManager.cpp
CXXSRCS += binder/Binder.cpp
CXXSRCS += binder/BpBinder.cpp
CXXSRCS += binder/BufferedTextOutput.cpp
CXXSRCS += binder/Debug.cpp
CXXSRCS += binder/FdTrigger.cpp
CXXSRCS += binder/IActivityManager.cpp
CXXSRCS += binder/IBatteryStats.cpp
CXXSRCS += binder/IInterface.cpp
CXXSRCS += binder/IMemory.cpp
CXXSRCS += binder/IPCThreadState.cpp
CXXSRCS += binder/IPermissionController.cpp
CXXSRCS += binder/IProcessInfoService.cpp
CXXSRCS += binder/IResultReceiver.cpp
CXXSRCS += binder/IServiceManager.cpp
CXXSRCS += binder/IShellCallback.cpp
CXXSRCS += binder/IUidObserver.cpp
CXXSRCS += binder/LazyServiceRegistrar.cpp
CXXSRCS += binder/MemoryBase.cpp
CXXSRCS += binder/MemoryDealer.cpp
CXXSRCS += binder/MemoryHeapBase.cpp
CXXSRCS += binder/Parcel.cpp
CXXSRCS += binder/ParcelableHolder.cpp
CXXSRCS += binder/ParcelFileDescriptor.cpp
CXXSRCS += binder/PermissionCache.cpp
CXXSRCS += binder/PermissionController.cpp
CXXSRCS += binder/PersistableBundle.cpp
CXXSRCS += binder/ProcessInfoService.cpp
CXXSRCS += binder/ProcessState.cpp
CXXSRCS += binder/Stability.cpp
CXXSRCS += binder/Static.cpp
CXXSRCS += binder/Status.cpp
CXXSRCS += binder/TextOutput.cpp
CXXSRCS += binder/Utils.cpp

include $(APPDIR)/Application.mk
