/* config.h. Generated by cmake from config.h.cmake */

#ifndef _DBUS_CONFIG_H
#define _DBUS_CONFIG_H

/* On Windows, we expect to be using msvcrt.dll-compatible printf
 * (%I64u instead of %llu) unless otherwise specified. This must be
 * done near the beginning of config.h, before we have included any
 * system headers that might check the value of this macro. */
#ifndef __USE_MINGW_ANSI_STDIO
#   define __USE_MINGW_ANSI_STDIO 0
#endif

/* generated by cmake macro autopackage */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/dbus/dbus/issues"

/* Define to the full name of this package. */
#define PACKAGE_NAME "dbus"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "dbus 1.15.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "dbus"

/* Define to the home page for this package. */
#define PACKAGE_URL "http://dbus.freedesktop.org"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.15.1"

/* defined by autotools package */
#define PACKAGE "dbus"
#define VERSION "1.15.1"


/*
 * Variables defined by AC_DEFINE in ../configure.ac
 * should be placed in this file
*/

/* AC_C_BIGENDIAN */
/* #undef WORDS_BIGENDIAN */

/* Opt-in to modern APIs and thread-safety for Solaris. In the Autotools
 * build system we do the equivalent of this by appending to CFLAGS
 * in configure.ac */
#ifdef __sun
# define __EXTENSIONS__
# define _POSIX_PTHREAD_SEMANTICS
# define _REENTRANT
# define _XOPEN_SOURCE 500
#endif

#define DBUS_DATADIR  "/etc"
#define DBUS_BINDIR   "/bin"
/* #undef DBUS_PREFIX */
#define DBUS_SYSTEM_CONFIG_FILE  "/etc/dbus-1/system.conf"
#define DBUS_SESSION_CONFIG_FILE "/etc/dbus-1/session.conf"
#define DBUS_SESSION_SOCKET_DIR "/var/run/dbus"
#define DBUS_DAEMON_NAME "dbusdaemon"
#ifndef DBUS_RPMSG_SERVER_CPUNAME
#define DBUS_SYSTEM_BUS_DEFAULT_ADDRESS  "unix:path=/var/run/dbus/system_bus_socket"
#else
#define DBUS_SYSTEM_BUS_DEFAULT_ADDRESS  "rpmsg:cpu="DBUS_RPMSG_SERVER_CPUNAME",name=dbus_socket"
#endif
#define DBUS_SESSION_BUS_CONNECT_ADDRESS  "unix:path=/var/run/dbus/session_bus_socket"
#define DBUS_MACHINE_UUID_FILE "/tmp/lib/dbus/machine-id"
#define DBUS_DAEMONDIR "/bin"
#define DBUS_RUNSTATEDIR "/var/run"

/* #undef DBUS_ENABLE_STATS */
#define ENABLE_TRADITIONAL_ACTIVATION

#define TEST_LISTEN       "unix:tmpdir=/tmp"

// test binaries
#define DBUS_EXEEXT ""

/* Some dbus features */
/* #undef DBUS_ENABLE_ANSI */
#define DBUS_ENABLE_VERBOSE_MODE 1
/* #undef DBUS_DISABLE_ASSERT */
#ifndef DBUS_DISABLE_ASSERT
#  define DBUS_ENABLE_ASSERT 1
#endif
/* #undef DBUS_DISABLE_CHECKS */
#ifndef DBUS_DISABLE_CHECKS
#  define DBUS_ENABLE_CHECKS 1
#endif
/* #undef DBUS_ENABLE_EMBEDDED_TESTS */
/* #undef DBUS_ENABLE_MODULAR_TESTS */
/* #undef DBUS_USE_OUTPUT_DEBUG_STRING */

/* xmldocs */
/* doxygen */
/* #undef DBUS_GCOV_ENABLED */

/* selinux */
/* kqueue */
/* #undef HAVE_CONSOLE_OWNER_FILE */

/* #undef DBUS_BUILD_X11 */
/* For the moment, the cmake build system doesn't have an equivalent of
 * the autoconf build system's --disable-x11-autolaunch */
#ifdef DBUS_BUILD_X11
# define DBUS_ENABLE_X11_AUTOLAUNCH 1
#endif

/* #undef DBUS_WITH_GLIB 1 */
/* #undef GLIB_VERSION_MIN_REQUIRED GLIB_VERSION_2_38 */
/* #undef GLIB_VERSION_MAX_ALLOWED  G_ENCODE_VERSION(2,44) */

// headers
/* #undef HAVE_AFUNIX_H */
#define HAVE_ALLOCA_H 1
#define HAVE_BYTESWAP_H 1
/* #undef HAVE_CRT_EXTERNS_H */

/* Define to 1 if you have dirent.h */
#define   HAVE_DIRENT_H 1

/* Define to 1 if you have errno.h */
#define   HAVE_ERRNO_H 1

/* Define to 1 if you have inttypes.h */
#define   HAVE_INTTYPES_H 1

/* Define to 1 if you have io.h */
/* #undef HAVE_IO_H */

/* Define to 1 if you have locale.h */
#define   HAVE_LOCALE_H 1

/* Define to 1 if you have poll */
#define    HAVE_POLL 1

/* Define to 1 if you have signal.h */
#define   HAVE_SIGNAL_H 1

/* Define to 1 if you have stdio.h */
#define   HAVE_STDIO_H 1

#define HAVE_SYSLOG_H 1
/* #undef HAVE_SYS_EVENTS_H */
/* #undef HAVE_SYS_INOTIFY_H */
#define HAVE_SYS_PRCTL_H 1
#define HAVE_SYS_RANDOM_H 1
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have sys/time.h */
#define    HAVE_SYS_TIME_H 1

/* Define to 1 if you have unistd.h */
#define   HAVE_UNISTD_H 1

/* Define to 1 if you have ws2tcpip.h */
/* #undef HAVE_WS2TCPIP_H */

// symbols
/* Define to 1 if you have backtrace */
#define   HAVE_BACKTRACE 1

/* Define to 1 if you have getgrouplist */
/* #undef HAVE_GETGROUPLIST */

/* Define to 1 if you have getpeerucred */
/* #undef HAVE_GETPEERUCRED */

/* Define to 1 if you have nanosleep */
#define   HAVE_NANOSLEEP 1

/* Define to 1 if you have getpwnam_r */
#define   HAVE_GETPWNAM_R 1

/* Define to 1 if you have socketpair */
#define   HAVE_SOCKETPAIR 1

/* Define to 1 if you have setenv */
#define   HAVE_SETENV 1

/* Define to 1 if you have unsetenv */
#define   HAVE_UNSETENV 1

/* Define to 1 if you have clearenv */
#define   HAVE_CLEARENV 1

/* Define to 1 if you have closefrom */
/* #undef HAVE_CLOSEFROM */

/* Define to 1 if you have close_range */
/* #undef HAVE_CLOSE_RANGE */

/* Define to 1 if you have writev */
#define   HAVE_WRITEV 1

/* Define to 1 if you have socklen_t */
#define   HAVE_SOCKLEN_T 1

/* Define to 1 if you have setlocale */
#define   HAVE_SETLOCALE 1

/* Define to 1 if you have localeconv */
#define   HAVE_LOCALECONV 1

/* Define to 1 if you have pip2 */
#define   HAVE_PIPE2 1

#define   HAVE_ACCEPT4 1

/* #undef HAVE_INOTIFY_INIT1 */
#define HAVE_GETRANDOM 1
/* #undef HAVE_GETRLIMIT */
#define HAVE_PRCTL 1
/* #undef HAVE_PRLIMIT */
#define HAVE_RAISE 1
/* #undef HAVE_SETRLIMIT */
#define HAVE_UNIX_FD_PASSING 1
/* #undef HAVE_SYSTEMD */

/* Define to use epoll(4) on Linux */
#define DBUS_HAVE_LINUX_EPOLL 1

/* Use the gcc __sync extension */
#define DBUS_USE_SYNC 1

/* #undef HAVE_SETRESUID */
/* #undef HAVE_GETRESUID */
/* whether -export-dynamic was passed to libtool */
/* #undef DBUS_BUILT_R_DYNAMIC */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif

// structs
/* Define to 1 if you have struct cmsgred */
/* #undef HAVE_CMSGCRED */

/* #undef FD_SETSIZE */

#define DBUS_USER "messagebus"
/* #undef DBUS_TEST_USER */
/* #undef DBUS_TEST_EXEC */

// system type defines
#if defined(_WIN32) || defined(_WIN64) || defined (_WIN32_WCE)
# define DBUS_WIN
# ifdef _WIN32_WCE
#  define DBUS_WINCE
# else
#  define DBUS_WIN32
   /* Define to the minimum supported Windows version (0x0600 is Vista) */
#  define _WIN32_WINNT 0x0600
# endif
#else
# define DBUS_UNIX
#endif

#if defined(_WIN32) || defined(_WIN64)
// mingw mode_t
# ifdef HAVE_STDIO_H
#  include <stdio.h>
# endif
# ifndef _MSC_VER
#  define uid_t int
#  define gid_t int
# else
   typedef int mode_t;
# endif
#endif	// defined(_WIN32) || defined(_WIN64)

#ifdef interface
#undef interface
#endif

#ifndef SIGHUP
#define SIGHUP	1
#endif

#ifdef DBUS_WIN
#define FD_SETSIZE
#endif

#define HAVE_DECL_ENVIRON 1
#define HAVE_DECL_LOG_PERROR 1
#define HAVE_DECL_MSG_NOSIGNAL 1

static inline int setsid(void)
{
  return 0;
}

static inline int setgroups(int size, const void *list)
{
  return 0;
}

#endif  // _DBUS_CONFIG_H
