#include <nuttx/config.h>

#define THORVG_VERSION_STRING "0.10.0"

#define THORVG_CAPI_BINDING_SUPPORT 1
#define THORVG_SW_RASTER_SUPPORT 1

#ifdef CONFIG_THORVG_SVG_LOADER_SUPPORT
#define THORVG_SVG_LOADER_SUPPORT 1
#endif

#ifdef CONFIG_THORVG_PNG_LOADER_SUPPORT
#define THORVG_PNG_LOADER_SUPPORT 1
#endif

#ifdef CONFIG_THORVG_TVG_LOADER_SUPPORT
#define THORVG_TVG_LOADER_SUPPORT 1
#endif

#ifdef CONFIG_THORVG_JPG_LOADER_SUPPORT
#define THORVG_JPG_LOADER_SUPPORT 1
#endif

#ifdef CONFIG_THORVG_LOTTIE_LOADER_SUPPORT
#define THORVG_LOTTIE_LOADER_SUPPORT 1
#endif

#ifdef CONFIG_THORVG_TTF_LOADER_SUPPORT
#define THORVG_TTF_LOADER_SUPPORT 1
#endif

#ifdef CONFIG_THORVG_WEBP_LOADER_SUPPORT
#define THORVG_WEBP_LOADER_SUPPORT 1
#endif
