#
# Copyright (C) 2020 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

CXXEXT = .cc

CXXSRCS += libchrome/base/at_exit.cc
CXXSRCS += libchrome/base/base64.cc
CXXSRCS += libchrome/base/base_switches.cc
CXXSRCS += libchrome/base/build_time.cc
CXXSRCS += libchrome/base/callback_helpers.cc
CXXSRCS += libchrome/base/callback_internal.cc
CXXSRCS += libchrome/base/command_line.cc
CXXSRCS += libchrome/base/cpu.cc
CXXSRCS += libchrome/base/debug/activity_tracker.cc
CXXSRCS += libchrome/base/debug/alias.cc
CXXSRCS += libchrome/base/debug/debugger.cc
CXXSRCS += libchrome/base/debug/debugger_posix.cc
CXXSRCS += libchrome/base/debug/dump_without_crashing.cc
CXXSRCS += libchrome/base/debug/stack_trace.cc
CXXSRCS += libchrome/base/debug/task_annotator.cc
CXXSRCS += libchrome/base/environment.cc
CXXSRCS += libchrome/base/feature_list.cc
CXXSRCS += libchrome/base/files/file.cc
CXXSRCS += libchrome/base/files/file_descriptor_watcher_posix.cc
CXXSRCS += libchrome/base/files/file_enumerator.cc
CXXSRCS += libchrome/base/files/file_enumerator_posix.cc
CXXSRCS += libchrome/base/files/file_path.cc
CXXSRCS += libchrome/base/files/file_path_constants.cc
CXXSRCS += libchrome/base/files/file_path_watcher.cc
CXXSRCS += libchrome/base/files/file_posix.cc
CXXSRCS += libchrome/base/files/file_tracing.cc
CXXSRCS += libchrome/base/files/file_util.cc
CXXSRCS += libchrome/base/files/file_util_posix.cc
CXXSRCS += libchrome/base/files/important_file_writer.cc
CXXSRCS += libchrome/base/files/memory_mapped_file.cc
CXXSRCS += libchrome/base/files/memory_mapped_file_posix.cc
CXXSRCS += libchrome/base/files/scoped_file.cc
CXXSRCS += libchrome/base/files/scoped_temp_dir.cc
CXXSRCS += libchrome/base/guid.cc
CXXSRCS += libchrome/base/json/json_parser.cc
CXXSRCS += libchrome/base/json/json_reader.cc
CXXSRCS += libchrome/base/json/json_string_value_serializer.cc
CXXSRCS += libchrome/base/json/json_writer.cc
CXXSRCS += libchrome/base/json/string_escape.cc
CXXSRCS += libchrome/base/lazy_instance_helpers.cc
CXXSRCS += libchrome/base/location.cc
CXXSRCS += libchrome/base/logging.cc
CXXSRCS += libchrome/base/md5.cc
CXXSRCS += libchrome/base/memory/ref_counted.cc
CXXSRCS += libchrome/base/memory/ref_counted_memory.cc
CXXSRCS += libchrome/base/memory/shared_memory_handle.cc
CXXSRCS += libchrome/base/memory/shared_memory_handle_posix.cc
CXXSRCS += libchrome/base/memory/weak_ptr.cc
CXXSRCS += libchrome/base/message_loop/incoming_task_queue.cc
CXXSRCS += libchrome/base/message_loop/message_loop.cc
CXXSRCS += libchrome/base/message_loop/message_loop_current.cc
CXXSRCS += libchrome/base/message_loop/message_loop_task_runner.cc
CXXSRCS += libchrome/base/message_loop/message_pump.cc
CXXSRCS += libchrome/base/message_loop/message_pump_default.cc
CXXSRCS += libchrome/base/message_loop/watchable_io_message_pump_posix.cc
CXXSRCS += libchrome/base/metrics/bucket_ranges.cc
CXXSRCS += libchrome/base/metrics/dummy_histogram.cc
CXXSRCS += libchrome/base/metrics/field_trial.cc
CXXSRCS += libchrome/base/metrics/field_trial_param_associator.cc
CXXSRCS += libchrome/base/metrics/histogram_base.cc
CXXSRCS += libchrome/base/metrics/histogram.cc
CXXSRCS += libchrome/base/metrics/histogram_functions.cc
CXXSRCS += libchrome/base/metrics/histogram_samples.cc
CXXSRCS += libchrome/base/metrics/histogram_snapshot_manager.cc
CXXSRCS += libchrome/base/metrics/metrics_hashes.cc
CXXSRCS += libchrome/base/metrics/persistent_histogram_allocator.cc
CXXSRCS += libchrome/base/metrics/persistent_memory_allocator.cc
CXXSRCS += libchrome/base/metrics/persistent_sample_map.cc
CXXSRCS += libchrome/base/metrics/sample_map.cc
CXXSRCS += libchrome/base/metrics/sample_vector.cc
CXXSRCS += libchrome/base/metrics/sparse_histogram.cc
CXXSRCS += libchrome/base/metrics/statistics_recorder.cc
CXXSRCS += libchrome/base/native_library.cc
CXXSRCS += libchrome/base/observer_list_threadsafe.cc
CXXSRCS += libchrome/base/path_service.cc
CXXSRCS += libchrome/base/pending_task.cc
CXXSRCS += libchrome/base/pickle.cc
CXXSRCS += libchrome/base/posix/file_descriptor_shuffle.cc
CXXSRCS += libchrome/base/posix/global_descriptors.cc
CXXSRCS += libchrome/base/posix/safe_strerror.cc
CXXSRCS += libchrome/base/process/internal_linux.cc
CXXSRCS += libchrome/base/process/kill.cc
CXXSRCS += libchrome/base/process/launch.cc
CXXSRCS += libchrome/base/process/memory_stubs.cc
CXXSRCS += libchrome/base/process/process_handle.cc
CXXSRCS += libchrome/base/process/process_handle_linux.cc
CXXSRCS += libchrome/base/process/process_handle_posix.cc
CXXSRCS += libchrome/base/process/process_info_linux.cc
CXXSRCS += libchrome/base/process/process_iterator.cc
CXXSRCS += libchrome/base/process/process_iterator_linux.cc
CXXSRCS += libchrome/base/process/process_metrics.cc
CXXSRCS += libchrome/base/process/process_posix.cc
CXXSRCS += libchrome/base/rand_util.cc
CXXSRCS += libchrome/base/rand_util_posix.cc
CXXSRCS += libchrome/base/run_loop.cc
CXXSRCS += libchrome/base/sequence_checker_impl.cc
CXXSRCS += libchrome/base/sequenced_task_runner.cc
CXXSRCS += libchrome/base/sequence_token.cc
CXXSRCS += libchrome/base/sha1.cc
CXXSRCS += libchrome/base/strings/pattern.cc
CXXSRCS += libchrome/base/strings/safe_sprintf.cc
CXXSRCS += libchrome/base/strings/string16.cc
CXXSRCS += libchrome/base/strings/string_number_conversions.cc
CXXSRCS += libchrome/base/strings/string_piece.cc
CXXSRCS += libchrome/base/strings/stringprintf.cc
CXXSRCS += libchrome/base/strings/string_split.cc
CXXSRCS += libchrome/base/strings/string_util.cc
CXXSRCS += libchrome/base/strings/string_util_constants.cc
CXXSRCS += libchrome/base/strings/sys_string_conversions_posix.cc
CXXSRCS += libchrome/base/strings/utf_string_conversions.cc
CXXSRCS += libchrome/base/strings/utf_string_conversion_utils.cc
CXXSRCS += libchrome/base/synchronization/atomic_flag.cc
CXXSRCS += libchrome/base/synchronization/condition_variable_posix.cc
CXXSRCS += libchrome/base/synchronization/lock.cc
CXXSRCS += libchrome/base/synchronization/lock_impl_posix.cc
CXXSRCS += libchrome/base/synchronization/waitable_event_posix.cc
CXXSRCS += libchrome/base/sys_info.cc
CXXSRCS += libchrome/base/sys_info_linux.cc
CXXSRCS += libchrome/base/task/cancelable_task_tracker.cc
CXXSRCS += libchrome/base/task_runner.cc
CXXSRCS += libchrome/base/third_party/icu/icu_utf.cc
CXXSRCS += libchrome/base/third_party/nspr/prtime.cc
CXXSRCS += libchrome/base/threading/platform_thread_internal_posix.cc
CXXSRCS += libchrome/base/threading/platform_thread_linux.cc
CXXSRCS += libchrome/base/threading/platform_thread_posix.cc
CXXSRCS += libchrome/base/threading/post_task_and_reply_impl.cc
CXXSRCS += libchrome/base/threading/scoped_blocking_call.cc
CXXSRCS += libchrome/base/threading/sequenced_task_runner_handle.cc
CXXSRCS += libchrome/base/threading/sequence_local_storage_map.cc
CXXSRCS += libchrome/base/threading/sequence_local_storage_slot.cc
CXXSRCS += libchrome/base/threading/simple_thread.cc
CXXSRCS += libchrome/base/threading/thread.cc
CXXSRCS += libchrome/base/threading/thread_checker_impl.cc
CXXSRCS += libchrome/base/threading/thread_collision_warner.cc
CXXSRCS += libchrome/base/threading/thread_id_name_manager.cc
CXXSRCS += libchrome/base/threading/thread_local_storage.cc
CXXSRCS += libchrome/base/threading/thread_local_storage_posix.cc
CXXSRCS += libchrome/base/threading/thread_restrictions.cc
CXXSRCS += libchrome/base/threading/thread_task_runner_handle.cc
CXXSRCS += libchrome/base/time/clock.cc
CXXSRCS += libchrome/base/time/default_clock.cc
CXXSRCS += libchrome/base/time/default_tick_clock.cc
CXXSRCS += libchrome/base/timer/elapsed_timer.cc
CXXSRCS += libchrome/base/timer/timer.cc
CXXSRCS += libchrome/base/time/tick_clock.cc
CXXSRCS += libchrome/base/time/time.cc
CXXSRCS += libchrome/base/time/time_conversion_posix.cc
CXXSRCS += libchrome/base/time/time_exploded_posix.cc
CXXSRCS += libchrome/base/time/time_now_posix.cc
CXXSRCS += libchrome/base/time/time_override.cc
CXXSRCS += libchrome/base/unguessable_token.cc
CXXSRCS += libchrome/base/value_iterators.cc
CXXSRCS += libchrome/base/values.cc
CXXSRCS += libchrome/base/version.cc
CXXSRCS += libchrome/base/vlog.cc
CXXSRCS += libchrome/nuttx/base/debug/stack_trace_posix.cc
CXXSRCS += libchrome/nuttx/base/memory/shared_memory_posix.cc
CXXSRCS += libchrome/nuttx/base/message_loop/message_pump_glib.cc
CXXSRCS += libchrome/nuttx/base/message_loop/message_pump_libevent.cc
CXXSRCS += libchrome/nuttx/base/sys_info_posix.cc

CXXFLAGS += -DOS_POSIX -D_POSIX_MONOTONIC_CLOCK=1
CXXFLAGS += -Wno-undef -Wno-shadow -Wno-unused-variable -Wno-unused-but-set-variable
CXXFLAGS += -Wno-unused-value -Wno-sign-compare -D_GNU_SOURCE -fpermissive -fno-exceptions
CXXFLAGS += ${shell $(INCDIR) $(INCDIROPT) "$(CC)" libchrome/nuttx}

include $(APPDIR)/Application.mk
