#
# Copyright (C) 2023 Xiaomi Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include $(APPDIR)/Make.defs

CXXEXT = .cpp

CXXSRCS += libcutils/android_get_control_file.cpp
CXXSRCS += libcutils/ashmem-host.cpp
CXXSRCS += libcutils/canned_fs_config.cpp
CXXSRCS += libcutils/config_utils.cpp
CXXSRCS += libcutils/fs_config.cpp
CXXSRCS += libcutils/fs.cpp
CXXSRCS += libcutils/hashmap.cpp
CXXSRCS += libcutils/iosched_policy.cpp
CXXSRCS += libcutils/load_file.cpp
CXXSRCS += libcutils/multiuser.cpp
CXXSRCS += libcutils/native_handle.cpp
CXXSRCS += libcutils/partition_utils.cpp
CXXSRCS += libcutils/record_stream.cpp
CXXSRCS += libcutils/socket_inaddr_any_server_unix.cpp
CXXSRCS += libcutils/socket_local_client_unix.cpp
CXXSRCS += libcutils/socket_local_server_unix.cpp
CXXSRCS += libcutils/socket_network_client_unix.cpp
CXXSRCS += libcutils/sockets_unix.cpp
CXXSRCS += libcutils/sockets.cpp
CXXSRCS += libcutils/str_parms.cpp

include $(APPDIR)/Application.mk
